name: Deploy to S3

on:
  push:
    branches:
      - main   # change if you deploy from another branch

permissions:
  id-token: write   # Required for OIDC
  contents: read    # To fetch repo contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::673181687487:role/githubs3deployer
          aws-region: ap-south-1   # change if your bucket is in another region

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://vijendra.quantsynapse.com --delete
